Make ErrSchema1 checkable via errors.Is()
google/go-containerregistry pull request #1721
Opened 2023-06-05 15:19 UTC by Laitr0n

The `TestGetSchema1` said it should fail based on media type while gave the unsupported MediaType. But it not return the true.

This fixes that problem by implementing an `Is()` function on `ErrSchema1`
so that `errors.Is()` can properly identify the error as an ErrSchema1.
Usage can now be: `errors.Is(err, &ErrSchema1{schema : "foo"})`

2023-06-05 15:46 UTC, imjasonh approved these changes

2023-06-05 15:46 UTC, imjasonh commented
cc @jonjohnsonjr

2023-06-05 16:09 UTC, jonjohnsonjr requested changes
I think embedding the mediaType that we saw is both unnecessary and makes this really complicated.

Can you update this to just be:

```go
var ErrSchema1 = errors.New("unsupported schema1 mediaType, see https://github.com/google/go-containerregistry/issues/377")
```

And fix any tests that it breaks?

2023-06-07 13:43 UTC, jonjohnsonjr approved these changes

2023-06-07 13:46 UTC, jonjohnsonjr requested changes
Oh that's clever. Added a couple suggestions so that we can keep the exact same error string but have the `%w` wrapping make `errors.Is` work.

I have a feeling someone, somewhere is checking for the string value of this error specifically because `errors.Is` doesn't work, so I want to avoid breaking that.

2023-06-07 13:46 UTC, jonjohnsonjr commented on pkg/v1/remote/descriptor.go
> +var ErrSchema1 = errors.New("unsupported schema1 mediaType, see https://github.com/google/go-containerregistry/issues/377")
```suggestion
var ErrSchema1 = errors.New("see https://github.com/google/go-containerregistry/issues/377")
```

2023-06-07 13:46 UTC, jonjohnsonjr commented on pkg/v1/remote/descriptor.go
> +	return fmt.Errorf("mediaType: %s, %w", schema, ErrSchema1)
```suggestion
	return fmt.Errorf("unsupported MediaType: %q, %w", schema, ErrSchema1)
```

2023-06-07 15:17 UTC, jonjohnsonjr approved these changes
thanks!

2023-06-14 17:37 UTC, merged